export const SERVER_ROUTES = {
  AUTH: {
    SIGN_IN: "/auth/sign-in",
    SIGN_UP: "/auth/sign-up",
    SIGN_OUT: "/auth/sign-out",
    REFRESH: "/auth/refresh",
  },
  SETTINGS: {
    GENERAL: "/settings/general",
    UI_DISPLAY: "/settings/ui-display",
    UNITS: "/settings/units",
    DATA_TIME: "/settings/data-time",
    ALARMS: "/settings/alarms",
    SIGNALS: "/settings/signals",
    CHOKE_PUMPS: "/settings/choke-pumps",
    AUTO_CONTROL: "/settings/auto-control",
    HYDRAULICS_MODEL: "/settings/hydraulics-model",
    ABOUT_DIAGNOSTICS: "/settings/about-diagnostics",
  },
  NETWORK: {
    SOURCES: "/network/sources",
    SOURCES_OPTIONS: "/network/sources/options",
    PROTOCOLS: "/network/protocols",
    ROUTING: "/network/routing",
    SECURITY: "/network/security",
    DIAGNOSTICS: "/network/diagnostics",
  },
  MUD_PROPERTIES: {
    OVERVIEW: "/mud-properties/overview",
    RHEOLOGY: "/mud-properties/rheology",
    DENSITY: "/mud-properties/density",
    TEMPERATURE: "/mud-properties/temperature",
    GAS: "/mud-properties/gas",
    CALIBRATION: "/mud-properties/calibration",
    SUMMARY: "/mud-properties/summary",
  },
  DAQ: {
    DISPLAY: "/daq/display",
    STREAMING: "/daq/streaming",
    NOTIFICATIONS: "/daq/notifications",
    LOG_ANALYSIS: "/daq/log-analysis",
    SENSOR_PERMS: "/daq/sensor-perms",
    CALIBRATION: "/daq/calibration",
    HYDRAULICS: "/daq/hydraulics",
    SYSTEM_SETTINGS: "/daq/system-settings",
    DOWNLOADS: "/daq/downloads",
  },
};
